---
- hosts: 127.0.0.1
#  become_method: sudo
 # become_user: root
 # become: yes
  connection: local
  tasks:
    - command: echo {{ item }}
      with_items: [ 0, 2, 4, 6, 8, 10 ]
      when: item > 8
